config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
  delete '/logout', to: 'sessions#destroy'
  post '/message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user

    validates :body, presence: true

    scope :custom_display, -> { order(:created_at).last(50)}
    # Ex:- scope :active, -> {where(:active => true)}
   
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    
    validates :username, presence: true, length: {minimum:3,maximum:15}, uniqueness: {case_sensitive:false}
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !! current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Devam Etmek İçin Öncelikle Giriş Yapmalısınız!"
      redirect_to login_path
    end
  end


end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user, only: [:index]
    
    def index
        @message = Message.new
        @messages = Message.custom_display
        @users = User.all
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    def new

    end
    
    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", 
                                            mod_message: message_render(message)
        end
        
    end

    def destroy

    end

    private

    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message:message})
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    before_action :logged_in_redirect
    def new

    end
    
    def create
        user = User.new(user_params)
        if user.save
            flash[:success] = "Başarıyla Kayıt Oldunuz"
            session[:user_id] = user.id
            cookies[:user_id] = user.id
            redirect_to root_path
        else
            flash.now[:error] ="Kayıt Olurken Bir Hata Oluştu"
            render 'new'
        end
    end

    private

    def user_params
        params.require(:registration).permit(:username, :password)
    end

    def logged_in_redirect
        if logged_in?
            flash[:error] = "Zaten Giriş Yaptınız"
            redirect_to root_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    def new

    end
    
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            cookies[:user_id] = user.id
            flash[:success] = "Başarıyla Giriş Yaptınız"
            redirect_to root_path
        else
            flash.now[:error] ="Giriş Yaparken Bir Hata Oluştu"
            render 'new'
        end
        
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Başarıyla Çıkış Yaptınız"
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:error] = "Zaten Giriş Yaptınız"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular green coffee icon"></i>
  ~ChatBoard~
</h4>


<div class="ui two column grid container">

    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui medium feed" id="message-container">
                    <%= render @messages%>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class:"ui reply form", role:"form "}, url: message_path, remote: true) do |form|%>
                    <div class="field">
                        <div class="ui fluid icon input ">
                            <%= form.text_field :body, placeholder:"Mesajınızı Yazın..."%>
                            <%= form.button '<i class="icon bordered inverted green edit"></i>'.html_safe %>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <h4 class="ui header" id="users-header">
                <i class="users green icon"></i>
                <div class="content">
                    Çevrimiçi Kullanıcılar
                </div>
            </h4>
            
            <div class="ui middle aligned animated celled list" id="online-users">
            <% @users.each do |user|%>
                <% if user.online %>
                
                    <div class="item" >
                        <i class="user green icon"></i>
                        <div class="content">
                        <div class="header"><%= user.username%></div>
                        </div>
                    </div>
                    
                <%end%>
            <%end%>
            </div>
        </div>
    </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type,message|%>
    <div class="ui <%=type%> message transition">
    <i class="close icon"></i>
    <div class="header">
        <%= message %>
    </div>
    </div>
<%end%>

app/views/layouts/_navigation.html.erb
<div class="ui inverted large menu">
    <div class="ui container">
       <%=link_to "ChatBoard", root_path, class:"item"%>
    <div class="right menu">
        <div class="ui dropdown item">
        Hesap <i class="dropdown icon"></i>
        <div class="menu">
            <%if logged_in?%>
                <%= link_to "Çıkış Yap", logout_path, method: :delete, class:"item"%>
            <%else%>
                <%= link_to "Giriş Yap", login_path, class:"item"%>
                <%= link_to "Kayıt Ol", signup_path, class:"item"%>
            <%end%>
        </div>
        </div>
        <div class="item">
            <%= link_to "Giriş Yap", login_path, class:"ui green button"%>
        </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatBoardApp</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    

    <div class="ui container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    
        <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body%>
        </div>
        </div>
    
</div>